# Generated by Django 4.2 on 2025-12-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("organization", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Job", "Job"),
                            ("Internship", "Internship"),
                            ("NSS", "NSS"),
                            ("Masters", "Masters"),
                            ("PhD", "PhD"),
                            ("Workshop", "Workshop"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("application_link", models.URLField()),
                ("deadline", models.DateTimeField()),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Opportunities",
                "ordering": ["deadline"],
            },
        ),
    ]
