# Generated by Django 4.2 on 2025-12-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="type",
            field=models.CharField(
                choices=[
                    ("Job", "Job"),
                    ("Internship", "Internship"),
                    ("NSS", "NSS"),
                    ("Research", "Research"),
                    ("Undergarduate", "Undergarduate"),
                    ("Postgraduate", "Postgraduate"),
                    ("Masters", "Masters"),
                    ("PhD", "PhD"),
                    ("Workshop", "Workshop"),
                    ("Conference", "Conference"),
                    ("Scholarship", "Scholarship"),
                    ("Other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
