# Generated by Django 4.2 on 2025-12-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Event title/name", max_length=200),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the event"),
                ),
                ("date", models.DateField(help_text="Date of the event")),
                ("start_time", models.TimeField(help_text="Event start time")),
                ("end_time", models.TimeField(help_text="Event end time")),
                (
                    "location",
                    models.CharField(help_text="Event venue/location", max_length=200),
                ),
                (
                    "event_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional event banner/poster image",
                        null=True,
                        upload_to="events/images/",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as featured event (shows on homepage)",
                    ),
                ),
                (
                    "registration_required",
                    models.BooleanField(
                        default=False, help_text="Whether event requires registration"
                    ),
                ),
                (
                    "registration_link",
                    models.URLField(
                        blank=True,
                        help_text="External registration link (optional)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["date", "start_time"],
            },
        ),
    ]
