# Generated by Django 6.0 on 2025-12-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dasa_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="year_group",
            field=models.IntegerField(
                blank=True, help_text="Year of completion (e.g., 2025)", null=True
            ),
        ),
    ]
