# Generated by Django 6.0 on 2025-12-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dasa_users", "0002_alter_profile_year_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="year_group",
            field=models.IntegerField(null=True),
        ),
    ]
