# Generated by Django 4.2 on 2025-12-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dasa_users", "0003_alter_profile_year_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Enable maintenance mode to restrict user access",
                    ),
                ),
                (
                    "allow_registration",
                    models.BooleanField(
                        default=True, help_text="Allow new users to register"
                    ),
                ),
                (
                    "current_academic_year",
                    models.CharField(
                        default="2024/2025",
                        help_text="Current academic year (e.g., 2024/2025)",
                        max_length=20,
                    ),
                ),
                (
                    "current_semester",
                    models.IntegerField(
                        choices=[(1, "Semester 1"), (2, "Semester 2")],
                        default=1,
                        help_text="Current semester",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configuration",
            },
        ),
    ]
