# Generated by Django 4.2 on 2025-12-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dasa_users", "0004_systemconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="college",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CoS", "College of Science"),
                    ("CoE", "College of Engineering"),
                    ("CoHS", "College of Health Sciences"),
                    ("CABE", "College of Art and Built Environment"),
                    ("CoHSS", "College of Humanities and Social Sciences"),
                    ("CANR", "College of Agriculture and Natural Resources"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="hall_of_residence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Katanga", "University Hall (Katanga)"),
                    ("Conti", "Unity Hall (Conti)"),
                    ("Indece", "Independence Hall"),
                    ("Republic", "Republic Hall"),
                    ("Queens", "Queen Elizabeth II Hall"),
                    ("Africa", "Africa Hall"),
                    ("Off-Campus", "Off-Campus/Hostel"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="hometown",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="program_of_study",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="student_id",
            field=models.CharField(
                blank=True,
                help_text="KNUST Student ID",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="year_group",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
