# Generated by Django 4.2 on 2025-12-14 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WelfareReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Harassment", "Harassment"),
                            ("Academic", "Academic"),
                            ("Accommodation", "Accommodation"),
                            ("Financial", "Financial"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the issue"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Optional location (e.g., 'Katanga Block B')",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, help_text="Submit anonymously"),
                ),
                (
                    "contact_info",
                    models.CharField(
                        blank=True,
                        help_text="Optional contact information for follow-up",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Investigating", "Investigating"),
                            ("Resolved", "Resolved"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who submitted the report (null if anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="welfare_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Welfare Report",
                "verbose_name_plural": "Welfare Reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
