# Generated by Django 4.2 on 2025-12-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title/caption for the media",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("General", "General"),
                            ("Sports", "Sports"),
                            ("Cultural", "Cultural"),
                            ("Politics", "Politics"),
                            ("Excursion", "Excursion"),
                        ],
                        default="General",
                        help_text="Category of the media item",
                        max_length=20,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("Image", "Image"), ("Video", "Video")],
                        default="Image",
                        help_text="Type of media (Image or Video)",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload image file (for Image media type)",
                        null=True,
                        upload_to="gallery/images/",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Upload video file (for Video media type)",
                        null=True,
                        upload_to="gallery/videos/",
                    ),
                ),
                (
                    "video_thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail image for video preview",
                        null=True,
                        upload_to="gallery/thumbnails/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Gallery Item",
                "verbose_name_plural": "Gallery Items",
                "ordering": ["-created_at"],
            },
        ),
    ]
