from django.db import models


class Announcement(models.Model):
    """
    Model for system-wide announcements and notifications.

    Announcements can be created manually by admins or automatically
    generated by signals (e.g., when new events are created).
    """

    PRIORITY_CHOICES = [
        ('Normal', 'Normal'),
        ('High', 'High'),
    ]

    title = models.CharField(
        max_length=200,
        help_text="Announcement title"
    )

    message = models.TextField(
        help_text="Announcement message/content"
    )

    priority = models.CharField(
        max_length=10,
        choices=PRIORITY_CHOICES,
        default='Normal',
        help_text="Announcement priority level"
    )

    related_link = models.URLField(
        blank=True,
        null=True,
        help_text="Optional link related to this announcement"
    )

    is_active = models.BooleanField(
        default=True,
        help_text="Whether this announcement is active and should be displayed"
    )

    # Generic Relation fields to link to other models (Event, LostItem, etc.)
    from django.contrib.contenttypes.fields import GenericForeignKey
    from django.contrib.contenttypes.models import ContentType

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    content_object = GenericForeignKey('content_type', 'object_id')

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Announcement'
        verbose_name_plural = 'Announcements'

    def __str__(self):
        priority_icon = '🔴' if self.priority == 'High' else '🔵'
        return f"{priority_icon} {self.title}"
