# Generated by Django 4.2 on 2025-12-14 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Product title", max_length=200)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in GHS", max_digits=10
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Electronics", "Electronics"),
                            ("Hostel Essentials", "Hostel Essentials"),
                            ("Books", "Books"),
                            ("Fashion", "Fashion"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Used - Like New", "Used - Like New"),
                            ("Used - Good", "Used - Good"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(help_text="Product image", upload_to="market/"),
                ),
                ("description", models.TextField(help_text="Product description")),
                (
                    "whatsapp_number",
                    models.CharField(
                        help_text="WhatsApp number for contact", max_length=20
                    ),
                ),
                (
                    "is_sold",
                    models.BooleanField(default=False, help_text="Mark as sold"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
            },
        ),
    ]
