# Generated by Django 4.2 on 2025-12-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Announcement title", max_length=200),
                ),
                ("message", models.TextField(help_text="Announcement message/content")),
                (
                    "priority",
                    models.CharField(
                        choices=[("Normal", "Normal"), ("High", "High")],
                        default="Normal",
                        help_text="Announcement priority level",
                        max_length=10,
                    ),
                ),
                (
                    "related_link",
                    models.URLField(
                        blank=True,
                        help_text="Optional link related to this announcement",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this announcement is active and should be displayed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "ordering": ["-created_at"],
            },
        ),
    ]
