# Generated by Django 4.2 on 2025-12-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Resource title (e.g., 'Calculus I Past Questions 2023')",
                        max_length=200,
                    ),
                ),
                (
                    "course_code",
                    models.CharField(
                        help_text="Course code (e.g., 'MATH 122')", max_length=20
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload PDF file", upload_to="resources/pasco/"
                    ),
                ),
                (
                    "college",
                    models.CharField(
                        choices=[
                            ("CoS", "College of Science"),
                            ("CoE", "College of Engineering"),
                            ("CoHS", "College of Health Sciences"),
                            ("CABE", "College of Art and Built Environment"),
                            ("CoHSS", "College of Humanities and Social Sciences"),
                            ("CANR", "College of Agriculture and Natural Resources"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (100, "100"),
                            (200, "200"),
                            (300, "300"),
                            (400, "400"),
                            (500, "500"),
                            (600, "600"),
                        ]
                    ),
                ),
                (
                    "semester",
                    models.IntegerField(choices=[(1, "Semester 1"), (2, "Semester 2")]),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("downloads", models.IntegerField(default=0, editable=False)),
            ],
            options={
                "verbose_name": "Academic Resource",
                "verbose_name_plural": "Academic Resources",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
