# Generated by Django 4.2 on 2025-12-14 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LostItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Lost", "Lost"), ("Found", "Found")],
                        help_text="Lost or Found",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Student ID", "Student ID"),
                            ("Keys", "Keys"),
                            ("Wallet", "Wallet"),
                            ("Gadget", "Gadget"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "student_name",
                    models.CharField(
                        blank=True,
                        help_text="For Student IDs - name on the ID",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image of the item",
                        null=True,
                        upload_to="lost_found/",
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description and location details"),
                ),
                (
                    "contact_info",
                    models.CharField(
                        help_text="Phone/WhatsApp for contact", max_length=100
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, help_text="Mark as resolved"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        help_text="User who reported the item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lost/Found Item",
                "verbose_name_plural": "Lost/Found Items",
                "ordering": ["-created_at"],
            },
        ),
    ]
