# Generated by Django 4.2 on 2025-12-13 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Executive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Executive position title (e.g., 'President', 'General Secretary')",
                        max_length=100,
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(
                        help_text="Sorting order (1 for President, 2 for Vice President, etc.)"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Short quote or manifesto snippet"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        help_text="Academic year (e.g., '2024/2025')", max_length=20
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the current executive council",
                    ),
                ),
                (
                    "official_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Official executive portrait. Falls back to user's profile picture if empty.",
                        null=True,
                        upload_to="executives/",
                    ),
                ),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The student holding this executive position",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executive_positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Executive",
                "verbose_name_plural": "Executives",
                "ordering": ["rank"],
                "unique_together": {("user", "academic_year")},
            },
        ),
    ]
