# Generated by Django 4.2 on 2025-12-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadership", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="executive",
            name="social_links",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Social media links: {'linkedin': 'url', 'twitter': 'url', 'instagram': 'url'}",
            ),
        ),
    ]
